package CPP.Absyn; // Java Package generated by the BNF Converter.

public class ETrue extends Exp {
    public ETrue() {
    }

    public <R, A> R accept(CPP.Absyn.Exp.Visitor<R, A> v, A arg) {
        return v.visit(this, arg);
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        return o instanceof ETrue;
    }

    public int hashCode() {
        return 37;
    }


}
